/**
 * Web Push registration.
 *
 * Turns a browser into something the alert dispatcher can reach while the app
 * is closed. Three things have to line up: a service worker to receive the
 * push, the user's permission to show it, and a subscription stored against
 * their account so the server knows where to send.
 *
 * Worth knowing what this cannot do. On iOS, Web Push only works once the site
 * has been added to the Home Screen — that is Apple's rule, not a gap here,
 * and no amount of client code changes it. `pushSupport()` reports that case
 * separately so the UI can say so rather than offering a button that silently
 * does nothing.
 */

import { supabase, TABLES } from '@/lib/supabase';

export type PushSupport =
  | 'ready'
  /** Everything works, but the user has to be asked. */
  | 'needs-permission'
  /** Asked and refused. Only the browser's own settings can undo this. */
  | 'denied'
  /** iOS Safari in a tab: works, but only once installed to the Home Screen. */
  | 'needs-install'
  /** No service worker or Push API at all. */
  | 'unsupported';

/** Whether this is iOS/iPadOS, where push requires an installed web app. */
function isIos(): boolean {
  if (typeof navigator === 'undefined') return false;
  return (
    /iPad|iPhone|iPod/.test(navigator.userAgent) ||
    // iPadOS 13+ reports itself as a Mac; the touch points give it away.
    (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)
  );
}

/** Whether the page is running as an installed app rather than in a tab. */
function isStandalone(): boolean {
  if (typeof window === 'undefined') return false;
  return (
    window.matchMedia?.('(display-mode: standalone)').matches ||
    // Safari's own non-standard flag, which is the only signal on iOS.
    (window.navigator as { standalone?: boolean }).standalone === true
  );
}

export function pushSupport(): PushSupport {
  if (typeof window === 'undefined') return 'unsupported';
  if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
    // On iOS this is what a plain tab looks like, and the honest advice there
    // is "install it", not "your browser cannot do this".
    return isIos() && !isStandalone() ? 'needs-install' : 'unsupported';
  }
  if (typeof Notification === 'undefined') return 'unsupported';
  if (Notification.permission === 'denied') return 'denied';
  if (Notification.permission === 'granted') return 'ready';
  return 'needs-permission';
}

/** The VAPID public key travels as base64url; the API wants raw bytes. */
function urlBase64ToUint8Array(base64: string): Uint8Array {
  const padded = base64.padEnd(base64.length + ((4 - (base64.length % 4)) % 4), '=');
  const raw = atob(padded.replace(/-/g, '+').replace(/_/g, '/'));
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  return out;
}

async function registerWorker(): Promise<ServiceWorkerRegistration> {
  // BASE_URL, because the app is served from a subpath on GitHub Pages and the
  // root on Netlify — a worker registered at "/sw.js" 404s on one of them, and
  // a worker's scope cannot rise above where it is served from.
  const base = import.meta.env.BASE_URL;
  const existing = await navigator.serviceWorker.getRegistration(base);
  if (existing) return existing;
  return navigator.serviceWorker.register(`${base}sw.js`, { scope: base });
}

/**
 * Subscribe this device and store it against the signed-in account.
 *
 * Idempotent: an existing subscription is reused and upserted by endpoint, so
 * opening the app twice does not produce two rows that each deliver a copy of
 * every alert.
 */
export async function enablePush(
  userId: string,
  vapidPublicKey: string,
): Promise<{ ok: boolean; error?: string }> {
  if (!supabase) return { ok: false, error: 'No backend is configured.' };
  if (!vapidPublicKey) {
    /* The key is generated by the dispatcher on its first run and published
       into app settings. Until that has happened there is nothing to subscribe
       against, and saying so is better than a browser error about an invalid
       applicationServerKey. */
    return { ok: false, error: 'Push is not set up on the server yet. Try again in a minute.' };
  }

  const support = pushSupport();
  if (support === 'unsupported') return { ok: false, error: 'This browser cannot receive push notifications.' };
  if (support === 'needs-install') {
    return { ok: false, error: 'On iPhone and iPad, add PanScreener to your Home Screen first — Safari only allows notifications for installed apps.' };
  }
  if (support === 'denied') {
    return { ok: false, error: 'Notifications are blocked for this site. Allow them in your browser settings, then try again.' };
  }

  if (Notification.permission !== 'granted') {
    const granted = await Notification.requestPermission();
    if (granted !== 'granted') return { ok: false, error: 'Notifications were not allowed.' };
  }

  try {
    const registration = await registerWorker();
    await navigator.serviceWorker.ready;

    const subscription =
      (await registration.pushManager.getSubscription()) ??
      (await registration.pushManager.subscribe({
        // Required by every browser: a push with no payload the user can see
        // is not allowed, and this is the flag that promises one.
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(vapidPublicKey),
      }));

    const json = subscription.toJSON();
    if (!json.keys?.p256dh || !json.keys?.auth) {
      return { ok: false, error: 'The browser returned an incomplete subscription.' };
    }

    const { error } = await supabase.from(TABLES.pushSubscriptions).upsert(
      {
        user_id: userId,
        endpoint: subscription.endpoint,
        p256dh: json.keys.p256dh,
        auth: json.keys.auth,
        user_agent: navigator.userAgent.slice(0, 300),
        failure_count: 0,
      },
      { onConflict: 'endpoint' },
    );

    if (error) return { ok: false, error: 'Could not save this device. Try again.' };
    return { ok: true };
  } catch {
    return { ok: false, error: 'This browser refused the subscription.' };
  }
}

/** Unsubscribe this device and forget it server-side. */
export async function disablePush(): Promise<{ ok: boolean }> {
  try {
    const registration = await navigator.serviceWorker.getRegistration(import.meta.env.BASE_URL);
    const subscription = await registration?.pushManager.getSubscription();
    if (subscription) {
      // Dropped from the database first. Unsubscribing locally and failing to
      // delete the row would leave the server pushing into an endpoint that
      // no longer exists, which it can only discover by failing.
      if (supabase) {
        await supabase.from(TABLES.pushSubscriptions).delete().eq('endpoint', subscription.endpoint);
      }
      await subscription.unsubscribe();
    }
    return { ok: true };
  } catch {
    return { ok: false };
  }
}

/** Whether this device currently holds a subscription. */
export async function pushEnabledHere(): Promise<boolean> {
  try {
    if (pushSupport() !== 'ready') return false;
    const registration = await navigator.serviceWorker.getRegistration(import.meta.env.BASE_URL);
    return Boolean(await registration?.pushManager.getSubscription());
  } catch {
    return false;
  }
}
